# Generated by Django 6.0.4 on 2026-04-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='available_balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='merchant',
            name='held_balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
