# Generated by Django 6.0.4 on 2026-04-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_merchant_available_balance_merchant_held_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='available_balance',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='held_balance',
        ),
    ]
