# Generated by Django 6.0.4 on 2026-04-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='response_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
