# Generated by Django 6.0.4 on 2026-04-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_merchant_available_balance_and_more'),
        ('ledger', '0002_ledger_delete_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='ledger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['merchant', 'transaction_type'], name='ledger_ledg_merchan_30c076_idx'),
        ),
    ]
